# makefile generated by mkold
CCFLAGS=-O
CC=CC
INCLDIR_INSTALL=$(LOCAL)/include
LIBDIR_INSTALL=$(LOCAL)/lib

COM.00 = $(INSTALLROOT)
# INSTALLROOT defined in the environment

DIR.00 = /lib
DIR.01 = $(COM.00)/lib
DIR.02 = $(COM.00)/include
DIR.03 = /.

real.a : real.D/real.o real.D/realio.o real.D/single.o real.D/bigit.o \
		real.D/exactio.o real.D/shift.o real.D/addition.o \
		real.D/mult.o real.D/division.o real.D/series.o \
		real.D/pow.o real.D/modf.o real.D/trig.o real.D/exp.o \
		real.D/plimit.o
	ar r real.a real.D/real.o real.D/realio.o real.D/single.o real.D/bigit.o real.D/exactio.o real.D/shift.o real.D/addition.o real.D/mult.o real.D/division.o real.D/series.o real.D/pow.o real.D/modf.o real.D/trig.o real.D/exp.o real.D/plimit.o

real.D/real.o : real.c exact.h real.h real.D/.created
	( : creating real.D ; if [ ! -d 'real.D' ] ; then mkdir 'real.D' ; fi ; cd 'real.D' && pwd ) ; $(CC) $(CCFLAGS) -I. -c real.c ; mv real.o real.D/real.o

real.D/.created :
	if [ ! -d real.D ] ; then ( : creating real.D ; if [ ! -d 'real.D' ] ; then mkdir 'real.D' ; fi ; cd 'real.D' && pwd ) ; fi$(newline)\
	touch real.D$(DIR.03)created

real.D/realio.o : realio.c exact.h real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c realio.c ; mv realio.o real.D/realio.o

real.D/single.o : single.c exact.h real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c single.c ; mv single.o real.D/single.o

real.D/bigit.o : bigit.c bigit.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c bigit.c ; mv bigit.o real.D/bigit.o

real.D/exactio.o : exactio.c exact.h real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c exactio.c ; mv exactio.o real.D/exactio.o

real.D/shift.o : shift.c exact.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c shift.c ; mv shift.o real.D/shift.o

real.D/addition.o : addition.c exact.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c addition.c ; mv addition.o real.D/addition.o

real.D/mult.o : mult.c exact.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c mult.c ; mv mult.o real.D/mult.o

real.D/division.o : division.c exact.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c division.c ; mv division.o real.D/division.o

real.D/series.o : series.c exact.h real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c series.c ; mv series.o real.D/series.o

real.D/pow.o : pow.c real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c pow.c ; mv pow.o real.D/pow.o

real.D/modf.o : modf.c real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c modf.c ; mv modf.o real.D/modf.o

real.D/trig.o : trig.c trig.h real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c trig.c ; mv trig.o real.D/trig.o

real.D/exp.o : exp.c exp.h real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c exp.c ; mv exp.o real.D/exp.o

real.D/plimit.o : plimit.c bigit.h real.h real.D/.created
	$(CC) $(CCFLAGS) -I. -c plimit.c ; mv plimit.o real.D/plimit.o

install : $(DIR.02)/real.h $(DIR.01)/real.a

$(DIR.02)/real.h : real.h
	cp real.h $(DIR.02)/real.h

$(DIR.01)/real.a : real.a
	cp real.a $(DIR.01)/real.a
null=
newline=;
sharp=#
